const GET_ERRORS = 'GET_ERRORS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const GET_ANIMALS_FROM_SHELTER = 'GET_ANIMALS_FROM_SHELTER'
const ADD_ANIMAL = 'ADD_ANIMAL'

export {
  GET_ERRORS,
  SET_CURRENT_USER,
  GET_ANIMALS_FROM_SHELTER,
  ADD_ANIMAL
}